##DATA CLEANING

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
Applications_Throughput_Project = pd.read_csv("/content/Applications_Throughput_Project(1) (1).csv")
Applications_Throughput_Project.head(5)

,Identifier,Secondary School Quintile,Matric Province,Matric Year,Did English Home Language,Did Pure Mathematics,Did Physical Sciences,APS Manual,LIFE SCIENCES,GEOGRAPHY,OTHER SOUTH AFRICAN LANGUAGE,LIFE ORIENTATION,ENGLISH,MATHEMATICS,PHYSICAL SCIENCES,ICT,AGRICULTURAL SCIENCE,BUSINESS STUDIES,OTHER,ACCOUNTING
0,00109fa2304bc0c2c945fd471556d548,3.0,WESTERN CAPE,2020.0,No,Yes,Yes,40.6,80.0,75.0,74.0,70.0,68.0,59.0,50.0,NaN,NaN,NaN,NaN,NaN
1,001201ad91584864df7d6eebffbaa5fe,5.0,WESTERN CAPE,2019.0,Yes,Yes,Yes,36.4,55.0,NaN,72.0,72.0,62.0,58.0,50.0,67.0,NaN,NaN,NaN,NaN
2,0019dfd54da7649115a88728970455a8,3.0,EASTERN CAPE,2020.0,No,Yes,Yes,39.7,70.0,53.0,82.0,75.0,67.0,65.0,60.0,NaN,NaN,NaN,NaN,NaN
3,002ab7dd5325a0beba733479d9fdb6f7,5.0,EASTERN CAPE,2019.0,Yes,Yes,Yes,32.8,51.0,NaN,81.0,91.0,50.0,43.0,42.0,NaN,61.0,NaN,NaN,NaN
4,002ca6075611147ebcb558e218b8111b,5.0,WESTERN CAPE,2019.0,Yes,No,No,32.0,29.0,NaN,72.0,55.0,50.0,78.0,NaN,NaN,NaN,53.0,38.0,NaN

In [ ]:
Applications_Throughput_Project.columns

Index(['Identifier', 'Secondary School Quintile', 'Matric Province',
       'Matric Year', 'Did English Home Language', 'Did Pure Mathematics',
       'Did Physical Sciences', 'APS Manual', 'LIFE SCIENCES', 'GEOGRAPHY',
       'OTHER SOUTH AFRICAN LANGUAGE', 'LIFE ORIENTATION', 'ENGLISH',
       'MATHEMATICS', 'PHYSICAL SCIENCES', 'ICT', 'AGRICULTURAL SCIENCE',
       'BUSINESS STUDIES', 'OTHER', 'ACCOUNTING'],
      dtype='object')

In [ ]:
Applications_Throughput_Project.shape

(6735, 20)

In [ ]:
Enrolments_Throughput= pd.read_csv("/content/Applications_Throughput_Project(1) (1).csv")
Enrolments_Throughput.head(5)

,Identifier,Secondary School Quintile,Matric Province,Matric Year,Did English Home Language,Did Pure Mathematics,Did Physical Sciences,APS Manual,LIFE SCIENCES,GEOGRAPHY,OTHER SOUTH AFRICAN LANGUAGE,LIFE ORIENTATION,ENGLISH,MATHEMATICS,PHYSICAL SCIENCES,ICT,AGRICULTURAL SCIENCE,BUSINESS STUDIES,OTHER,ACCOUNTING
0,00109fa2304bc0c2c945fd471556d548,3.0,WESTERN CAPE,2020.0,No,Yes,Yes,40.6,80.0,75.0,74.0,70.0,68.0,59.0,50.0,NaN,NaN,NaN,NaN,NaN
1,001201ad91584864df7d6eebffbaa5fe,5.0,WESTERN CAPE,2019.0,Yes,Yes,Yes,36.4,55.0,NaN,72.0,72.0,62.0,58.0,50.0,67.0,NaN,NaN,NaN,NaN
2,0019dfd54da7649115a88728970455a8,3.0,EASTERN CAPE,2020.0,No,Yes,Yes,39.7,70.0,53.0,82.0,75.0,67.0,65.0,60.0,NaN,NaN,NaN,NaN,NaN
3,002ab7dd5325a0beba733479d9fdb6f7,5.0,EASTERN CAPE,2019.0,Yes,Yes,Yes,32.8,51.0,NaN,81.0,91.0,50.0,43.0,42.0,NaN,61.0,NaN,NaN,NaN
4,002ca6075611147ebcb558e218b8111b,5.0,WESTERN CAPE,2019.0,Yes,No,No,32.0,29.0,NaN,72.0,55.0,50.0,78.0,NaN,NaN,NaN,53.0,38.0,NaN

In [ ]:
Enrolments_Throughput.shape

(6735, 20)

In [ ]:
Residence_Throughput= pd.read_csv("/content/Residence_Throughput_Project(1).csv")
Residence_Throughput.head(5)

,Identifier,Qualification Code,Years_in_Residence,Years_not_in_Residence,Prop_Years_in_Residence,Main_Building
0,002ab7dd5325a0beba733479d9fdb6f7,D3AGRM,4,2,0.666667,MURRAY HOUSE RES - WELLINGTON
1,0036d6a189650483fcfdbe6d2e1a6203,D3AGRM,3,1,0.750000,HOUSE MEIRING RES - WELLINGTON
2,0040397252e59abb5c3e31f9df293f64,D3HRMT,1,0,1.000000,CAPE SUITES
3,005dde1e54c30fca1fd31663d8c2f7b0,D3CSTN,2,3,0.400000,SERITI HOUSE RESIDENCE
4,005e146c672f58a27aca86da17b0dd0a,D3PHGY,3,0,1.000000,EWR: GREEN OAKS - GARDENS

In [ ]:
''"Check students that are in residence and enrolled for the qualification = D3HSPH"""
D3HSPH_Residence=Residence_Throughput[Residence_Throughput["Qualification Code"]=="D3HSPH"]
D3HSPH_Residence.shape[0]

61

In [ ]:
"""Merge the three datasets by Identifier by left join"""
merged_df=pd.merge(Enrolments_Throughput,Residence_Throughput, on="Identifier", how="outer")
merged_df=pd.merge(merged_df,Applications_Throughput_Project, on="Identifier", how="outer")
merged_df.head(5)

,Identifier,Secondary School Quintile_x,Matric Province_x,Matric Year_x,Did English Home Language_x,Did Pure Mathematics_x,Did Physical Sciences_x,APS Manual_x,LIFE SCIENCES_x,GEOGRAPHY_x,...,OTHER SOUTH AFRICAN LANGUAGE_y,LIFE ORIENTATION_y,ENGLISH_y,MATHEMATICS_y,PHYSICAL SCIENCES_y,ICT_y,AGRICULTURAL SCIENCE_y,BUSINESS STUDIES_y,OTHER_y,ACCOUNTING_y
0,00109fa2304bc0c2c945fd471556d548,3.0,WESTERN CAPE,2020.0,No,Yes,Yes,40.6,80.0,75.0,...,74.0,70.0,68.0,59.0,50.0,NaN,NaN,NaN,NaN,NaN
1,001201ad91584864df7d6eebffbaa5fe,5.0,WESTERN CAPE,2019.0,Yes,Yes,Yes,36.4,55.0,NaN,...,72.0,72.0,62.0,58.0,50.0,67.0,NaN,NaN,NaN,NaN
2,0019dfd54da7649115a88728970455a8,3.0,EASTERN CAPE,2020.0,No,Yes,Yes,39.7,70.0,53.0,...,82.0,75.0,67.0,65.0,60.0,NaN,NaN,NaN,NaN,NaN
3,002ab7dd5325a0beba733479d9fdb6f7,5.0,EASTERN CAPE,2019.0,Yes,Yes,Yes,32.8,51.0,NaN,...,81.0,91.0,50.0,43.0,42.0,NaN,61.0,NaN,NaN,NaN
4,002ca6075611147ebcb558e218b8111b,5.0,WESTERN CAPE,2019.0,Yes,No,No,32.0,29.0,NaN,...,72.0,55.0,50.0,78.0,NaN,NaN,NaN,53.0,38.0,NaN

In [ ]:
merged_df.shape

(6803, 44)

In [ ]:
"""Check for missing values in Main_Building in merged_df"""
merged_df["Main_Building"].isnull().sum()

np.int64(3443)

In [ ]:
merged_df.isnull().sum().sort_values(ascending=False)

ICT_y                             5988
ICT_x                             5988
AGRICULTURAL SCIENCE_x            5975
AGRICULTURAL SCIENCE_y            5975
ACCOUNTING_y                      5208
ACCOUNTING_x                      5208
BUSINESS STUDIES_x                4855
BUSINESS STUDIES_y                4855
GEOGRAPHY_x                       4303
GEOGRAPHY_y                       4303
OTHER_x                           3789
OTHER_y                           3789
Main_Building                     3443
Years_not_in_Residence            3443
Years_in_Residence                3443
Prop_Years_in_Residence           3443
Qualification Code                3443
PHYSICAL SCIENCES_y               2829
PHYSICAL SCIENCES_x               2829
LIFE SCIENCES_y                   2594
LIFE SCIENCES_x                   2594
LIFE ORIENTATION_x                 499
LIFE ORIENTATION_y                 499
OTHER SOUTH AFRICAN LANGUAGE_x     348
MATHEMATICS_x                      348
OTHER SOUTH AFRICAN LANGUAGE_y     348
MATHEMATICS_y                      348
ENGLISH_x                          324
ENGLISH_y                          324
Secondary School Quintile_y        196
Secondary School Quintile_x        196
Matric Province_y                  178
Matric Province_x                  178
Matric Year_x                        7
Matric Year_y                        7
Identifier                           0
Did English Home Language_x          0
Did Pure Mathematics_x               0
Did Physical Sciences_x              0
APS Manual_x                         0
Did English Home Language_y          0
Did Pure Mathematics_y               0
Did Physical Sciences_y              0
APS Manual_y                         0
dtype: int64

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6803 entries, 0 to 6802
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Identifier                      6803 non-null   object
 1   Secondary School Quintile_x     6607 non-null   float64
 2   Matric Province_x               6625 non-null   object
 3   Matric Year_x                   6796 non-null   float64
 4   Did English Home Language_x     6803 non-null   object
 5   Did Pure Mathematics_x          6803 non-null   object
 6   Did Physical Sciences_x         6803 non-null   object
 7   APS Manual_x                    6803 non-null   float64
 8   LIFE SCIENCES_x                 4209 non-null   float64
 9   GEOGRAPHY_x                     2500 non-null   float64
 10  OTHER SOUTH AFRICAN LANGUAGE_x  6455 non-null   float64
 11  LIFE ORIENTATION_x              6304 non-null   float64
 12  ENGLISH_x                       6479 non-null   float64
 13  MATHEMATICS_x                   6455 non-null   float64
 14  PHYSICAL SCIENCES_x             3974 non-null   float64
 15  ICT_x                           815 non-null    float64
 16  AGRICULTURAL SCIENCE_x          828 non-null    float64
 17  BUSINESS STUDIES_x              1948 non-null   float64
 18  OTHER_x                         3014 non-null   float64
 19  ACCOUNTING_x                    1595 non-null   float64
 20  Qualification Code              3360 non-null   object
 21  Years_in_Residence              3360 non-null   float64
 22  Years_not_in_Residence          3360 non-null   float64
 23  Prop_Years_in_Residence         3360 non-null   float64
 24  Main_Building                   3360 non-null   object
 25  Secondary School Quintile_y     6607 non-null   float64
 26  Matric Province_y               6625 non-null   object
 27  Matric Year_y                   6796 non-null   float64
 28  Did English Home Language_y     6803 non-null   object
 29  Did Pure Mathematics_y          6803 non-null   object
 30  Did Physical Sciences_y         6803 non-null   object
 31  APS Manual_y                    6803 non-null   float64
 32  LIFE SCIENCES_y                 4209 non-null   float64
 33  GEOGRAPHY_y                     2500 non-null   float64
 34  OTHER SOUTH AFRICAN LANGUAGE_y  6455 non-null   float64
 35  LIFE ORIENTATION_y              6304 non-null   float64
 36  ENGLISH_y                       6479 non-null   float64
 37  MATHEMATICS_y                   6455 non-null   float64
 38  PHYSICAL SCIENCES_y             3974 non-null   float64
 39  ICT_y                           815 non-null    float64
 40  AGRICULTURAL SCIENCE_y          828 non-null    float64
 41  BUSINESS STUDIES_y              1948 non-null   float64
 42  OTHER_y                         3014 non-null   float64
 43  ACCOUNTING_y                    1595 non-null   float64
dtypes: float64(33), object(11)
memory usage: 2.3+ MB

In [ ]:
#Treat missing values in the Years_in_Residence column by replacing them with 0
merged_df["Years_in_Residence"]= merged_df["Years_in_Residence"].fillna(0)
merged_df["Main_Building"]= merged_df["Main_Building"].fillna("Not_in_residence")

In [ ]:
merged_df.isnull().sum().sort_values(ascending=False)

ICT_y                             5988
ICT_x                             5988
AGRICULTURAL SCIENCE_x            5975
AGRICULTURAL SCIENCE_y            5975
ACCOUNTING_y                      5208
ACCOUNTING_x                      5208
BUSINESS STUDIES_x                4855
BUSINESS STUDIES_y                4855
GEOGRAPHY_x                       4303
GEOGRAPHY_y                       4303
OTHER_x                           3789
OTHER_y                           3789
Years_not_in_Residence            3443
Qualification Code                3443
Prop_Years_in_Residence           3443
PHYSICAL SCIENCES_x               2829
PHYSICAL SCIENCES_y               2829
LIFE SCIENCES_y                   2594
LIFE SCIENCES_x                   2594
LIFE ORIENTATION_y                 499
LIFE ORIENTATION_x                 499
OTHER SOUTH AFRICAN LANGUAGE_x     348
MATHEMATICS_y                      348
OTHER SOUTH AFRICAN LANGUAGE_y     348
MATHEMATICS_x                      348
ENGLISH_x                          324
ENGLISH_y                          324
Secondary School Quintile_x        196
Secondary School Quintile_y        196
Matric Province_y                  178
Matric Province_x                  178
Matric Year_y                        7
Matric Year_x                        7
Identifier                           0
Did Physical Sciences_x              0
APS Manual_x                         0
Did English Home Language_x          0
Did Pure Mathematics_x               0
Main_Building                        0
Years_in_Residence                   0
Did English Home Language_y          0
Did Pure Mathematics_y               0
Did Physical Sciences_y              0
APS Manual_y                         0
dtype: int64

In [ ]:
# A code that deletes all columns with more than  2000 missing values
treshold=2000
merged_df= merged_df.loc[:, merged_df.isnull().sum() < treshold
]

In [ ]:
merged_df.isnull().sum().sort_values(ascending=False)

LIFE ORIENTATION_x                499
LIFE ORIENTATION_y                499
OTHER SOUTH AFRICAN LANGUAGE_y    348
MATHEMATICS_x                     348
MATHEMATICS_y                     348
OTHER SOUTH AFRICAN LANGUAGE_x    348
ENGLISH_y                         324
ENGLISH_x                         324
Secondary School Quintile_x       196
Secondary School Quintile_y       196
Matric Province_y                 178
Matric Province_x                 178
Matric Year_y                       7
Matric Year_x                       7
Identifier                          0
Did Pure Mathematics_x              0
Did English Home Language_x         0
APS Manual_x                        0
Did Physical Sciences_x             0
Main_Building                       0
Years_in_Residence                  0
APS Manual_y                        0
Did Physical Sciences_y             0
Did Pure Mathematics_y              0
Did English Home Language_y         0
dtype: int64

In [ ]:
#Export the merged_df to a csv file
merged_df.to_csv(r'C:\\Users\\Mvusi Mrwetyana\\OneDrive\Documents\\Siyaphumelela_project_Datasets\\Merged_df.csv', index=False)

In [ ]:
# List of columns to convert to categorical data type
categorical_columns = ['Secondary School Quintile_x', 'Secondary School Quintile_y', 'Matric Year_x', 'Matric Year_y']
# Convert specified columns to categorical data type
merged_df[categorical_columns] = merged_df[categorical_columns].astype('category')

In [ ]:
Applications_Throughput_Project = pd.read_csv("/content/Applications_Throughput_Project(1) (1).csv")
Enrolments_Throughput= pd.read_csv("/content/Applications_Throughput_Project(1) (1).csv")
Residence_Throughput= pd.read_csv("/content/Residence_Throughput_Project(1).csv")

merged_df=pd.merge(Enrolments_Throughput,Residence_Throughput, on="Identifier", how="outer")
merged_df=pd.merge(merged_df,Applications_Throughput_Project, on="Identifier", how="outer")
merged_df["Years_in_Residence"]= merged_df["Years_in_Residence"].fillna(0)
merged_df["Main_Building"]= merged_df["Main_Building"].fillna("Not_in_residence")

treshold=2000
merged_df= merged_df.loc[:, merged_df.isnull().sum() < treshold
]

In [ ]:
# List of columns to convert to categorical data type
categorical_columns = ['Secondary School Quintile_x', 'Secondary School Quintile_y', 'Matric Year_x', 'Matric Year_y']
# Convert specified columns to categorical data type
merged_df[categorical_columns] = merged_df[categorical_columns].astype('category')

In [ ]:
"""Filter the merged_df to only include students that are enrolled for the Qualification Name='DIP IN HOSPITALITY & HOTEL MANAGEMENT' """
DIP_HOSPITALITY_HOTEL_MANAGEMENT=merged_df[merged_df["Qualification Name"]=="DIP IN HOSPITALITY & HOTEL MANAGEMENT"]
DIP_HOSPITALITY_HOTEL_MANAGEMENT.shape[0]

KeyError: 'Qualification Name'

In [ ]:
"""Code to export the DIP_HOSPITALITY_HOTEL_MANAGEMENT dataframe to a csv file"""
DIP_HOSPITALITY_HOTEL_MANAGEMENT.to_csv(r'C:\Users\Mvusi Mrwetyana\OneDrive\Documents\Siyaphumelela_project_Datasets\DIP_HOSPITALITY_HOTEL_MANAGEMENT.csv', index=False)

**PREPROCESSING**

In [ ]:
"""PERFORMING MY PROJECT EDA"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv("C:\\Users\\Mvusi Mrwetyana\\OneDrive\\Documents\\Siyaphumelela_project_Datasets\\DIP_HOSPITALITY_HOTEL_MANAGEMENT.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Mvusi Mrwetyana\\OneDrive\\Documents\\Siyaphumelela_project_Datasets\\DIP_HOSPITALITY_HOTEL_MANAGEMENT.csv'

In [ ]:
"check for columns with missing values and arrange them in descending order"
df.isnull().sum().sort_values(ascending=False)

In [ ]:
df.info()

In [ ]:
# List of columns to convert to categorical data type
categorical_columns = ['Secondary School Quintile', 'Matric Year', 'Cohort Year']
# Convert specified columns to categorical data type
df[categorical_columns] = df[categorical_columns].astype('category')

In [ ]:
df.info()

In [ ]:
"""Imputation of categorical variables with most frequent class"""
most_frequent_quintile= df['Secondary School Quintile'].mode()[0]
df['Secondary School Quintile'].fillna(most_frequent_quintile, inplace=True)

In [ ]:
df.shape

In [ ]:
df.isnull().sum().sort_values(ascending=False)

In [ ]:
most_freq_province= df['Matric Province'].mode()[0]
df['Matric Province'].fillna(most_freq_province, inplace=True)
df.isnull().sum().sort_values(ascending=False)

In [ ]:
##Imputing missing values in numeric variables using KNN Imputer
from sklearn.impute import KNNImputer
import pandas as pd

#Identify numeric columns
numeric_cols = df.select_dtypes(include='number').columns.tolist()
#Create KNN imputer object
imputer = KNNImputer(n_neighbors=5)
imputed_array = imputer.fit_transform(df[numeric_cols])
#Convert the imputed array back to a DataFrame
imputed_df = pd.DataFrame(imputed_array, columns=numeric_cols, index=df.index)
#Replace only target columns with their imputed values
target_columns= ["MATHEMATICS", "ENGLISH", "LIFE ORIENTATION","OTHER SOUTH AFRICAN LANGUAGE"]
df[target_columns] = imputed_df[target_columns]
df.isnull().sum().sort_values(ascending=False)

In [ ]:
#Removing redundant columns
df=df.drop(columns=["Qualification Code_x","Identifier", "Qualification Name 2"])

In [ ]:
#Replace "your_column_name" with the actual name of your column name
class_counts = df['Minimum Time'].value_counts()
print(class_counts)

In [ ]:
df.shape

In [ ]:
df["Current Student"].unique()

**EDA**

In [ ]:
df_EDA= pd.read_csv("C:\\Users\\Mvusi Mrwetyana\\OneDrive\\Documents\\Siyaphumelela_project_Datasets\\DIP_HOSPITALITY_HOTEL_MANAGEMENT.csv")

In [ ]:
df=pd.read_csv("C:\\Users\\Mvusi Mrwetyana\\OneDrive\\Documents\\Siyaphumelela_project_Datasets\\Merged_df.csv")

In [ ]:
df_EDA.head(5)

*1.1 Univariate analysis continous variable*

In [ ]:
def cont_plot(df, var):
    #var="Age at Enrolment"
    # Set plot style
    sns.set(style="whitegrid")

    # Create a figure with two subplots: histogram and box plot
    plt.figure(figsize=(12, 6))

    # Histogram
    plt.subplot(1, 2, 1)
    sns.histplot(df_EDA[var], bins=20, kde=True, color='skyblue')
    plt.title(var+' Distribution - Histogram')
    plt.xlabel(var)
    plt.ylabel('Frequency')

    # Box plot
    plt.subplot(1, 2, 2)
    sns.boxplot(x=df_EDA[var], color='lightgreen')
    plt.title(var+' Distribution - Box Plot')
    plt.xlabel(var)

    plt.tight_layout()
    plt.show()

In [ ]:
cont_plot(df_EDA, "APS Manual")

In [ ]:
#Univariate analysis for MATHEMATICS
cont_plot(df_EDA, "MATHEMATICS")

In [ ]:
cont_plot(df_EDA, "Age at Enrolment")

In [ ]:
cont_plot(df_EDA, "Matric Year")

In [ ]:
cont_plot(df_EDA, "OTHER SOUTH AFRICAN LANGUAGE")

In [ ]:
cont_plot(df_EDA, "LIFE ORIENTATION")

In [ ]:
cont_plot(df_EDA, "ENGLISH")

**Observations**

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

def plot_object(dataframe, column_name):
    """
    Plots a bar chart showing category frequencies with both frequency (inside bar)
    and proportion (above bar) labels.

    Parameters:
    - dataframe: pandas DataFrame
    - column_name: str, name of the categorical column to visualize
    """
    # Count frequencies and proportions
    value_counts = dataframe[column_name].value_counts()
    proportions = value_counts / len(dataframe)

    # Set plot style
    sns.set(style="whitegrid")
    plt.figure(figsize=(10, 6))

    # Bar plot
    ax = sns.barplot(x=value_counts.index, y=value_counts.values, palette="muted")

      # Annotate bars
    for i, (count, prop) in enumerate(zip(value_counts.values, proportions.values)):
        # Frequency inside bar
        ax.text(i, count * 0.5, f'{count}', ha='center', va='center',
                fontsize=11, color='black', fontweight='bold')
        # Proportion above bar
        ax.text(i, count + max(value_counts.values) * 0.02, f'{prop:.2%}',
                ha='center', fontsize=10, color='navy')

    plt.title(f'Distribution of {column_name}')
    plt.xlabel(column_name)
    plt.xticks(rotation=90)
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

In [ ]:
df_EDA.columns

In [ ]:
plot_object(df_EDA, "Secondary School Quintile")

In [ ]:
plot_object(df_EDA, "Gender")

In [ ]:
plot_object(df_EDA, 'Main_Building')

In [ ]:
#A code to to put all variables in the Main_Building to one variable called "stay_in_Res" and then have another variable for "Not in Residence"
df_EDA['stay_in_Res'] = np.where(df_EDA['Main_Building'].isin(['CATSVILLE RESIDENCE: BLOCK E',
       'CITY EDGE RESIDENCE', 'CATSVILLE RESIDENCE: BLOCK G',
       'HANOVER STREET RESIDENCE', '10 PLEIN STREET (SOUTH POINT)',
       'NEW MARKET JUNCTION - BLOCK A', 'NEW MARKET JUNCTION (BLOCK B)',
       'SOUTH POINT ORCHARDS: BLOCK B', 'MOUNTAIN HOUSE',
       'PRESIDENT HOUSE (SOUTHPOINT)', 'CATSVILLE RESIDENCE: BLOCK H',
       'CATSVILLE RESIDENCE: BLOCK K', 'VOGUE HOUSE',
       '12 PLEIN STREET (SOUTH POINT)', 'NEW MARKET JUNCTION (BLOCK C)']), 'In Residence', 'Not in Residence')

In [ ]:
df_EDA['stay_in_Res'].value_counts()

In [ ]:
df_EDA["Main_Building"].unique()

In [ ]:
plot_object(df_EDA, "stay_in_Res")

In [ ]:
plot_object(df_EDA, 'Previous Activity Desc')

In [ ]:
plot_object(df_EDA,'Ethnic Group Name')

In [ ]:
plot_object(df_EDA, 'Minimum Time')

In [ ]:
plot_object(df_EDA,'Ften Status This Year')

In [ ]:
plot_object(df_EDA,  'Current Student')

In [ ]:
plot_object(df_EDA, 'Did Pure Mathematics')

In [ ]:
plot_object(df_EDA,'Matric Province')

In [ ]:
plot_object(df_EDA, 'Did Physical Sciences')

In [ ]:
plot_object(df_EDA,'Did English Home Language')

**FEATURE ENCODING**

In [ ]:
df3=df.copy()

In [ ]:
df3["Main_Building"] = df3["Main_Building"].apply(lambda x: "Not_in_residence" if x == "Not_in_residence" else "In_residence")

In [ ]:
df3.head(5)

In [ ]:
df2=df.copy()
non_numeric_cols = df2.select_dtypes(exclude='number').columns.tolist()
for column in non_numeric_cols:
    print(column)
    print( df2[column].unique())
    print("-"*50)

In [ ]:
##Binary Encoding
#Create a copy to avoid modifying the original dataframe
df_encoded = df2.copy()
#Encode Yes/No columns to 1/0
yes_no_cols = [
"Did English Home Language",
"Did Pure Mathematics",
"Did Physical Sciences","Minimum Time","Current Student"
]
for col in yes_no_cols:
    df_encoded[col] = df_encoded[col].map({"Yes": 1, "No": 0})
#Encode Gender: Female=0, Male=1
df_encoded['Gender'] = df_encoded['Gender'].map({'FEMALE': 0, 'MALE': 1})

#Encode Cohort Year: 2021=0, 2022=1
df_encoded['Cohort Year'] = df_encoded['Cohort Year'].map({2021: 0, 2022: 1})
df3=df_encoded.copy()

In [ ]:
df3.info()

In [ ]:
non_numeric_cols = df3.select_dtypes(exclude='number').columns.tolist()
print(non_numeric_cols)

In [ ]:
for column in non_numeric_cols:
    print(column)
    print( df3[column].unique())
    print("-"*50)

In [ ]:
df3["Main_Building"].unique()

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import category_encoders as ce

In [ ]:
#Define features and target variable
target = "Minimum Time"
target_encode_cols = [
"Main_Building",
"Secondary School Quintile",
 "Matric Province",
"Matric Year",
"Language Name",
"Ften Status This Year",
"Previous Activity Desc",
"Ethnic Group Name"
]

#Split the full dataframe into training and testing sets
train_df, test_df = train_test_split(
df3, test_size=0.2, random_state=5, stratify=df3[target]
)
# Step 3: Separate features and target as proper pandas Series
X_train = train_df.drop(columns=[target])
y_train = train_df[target] #  This is a pandas Series
y_train = pd.Series(y_train.tolist(), index=y_train.index,name='Minimum Time')
X_test = test_df.drop(columns=[target])
y_test = test_df[target] #  Also a pandas Series
y_test = pd.Series(y_test.tolist(), index=y_test.index,name='Minimum Time')
#Step 4: Apply target encoding
encoder = ce.TargetEncoder(cols=target_encode_cols)
X_train_encoded = encoder.fit_transform(X_train, y_train)
X_test_encoded = encoder.transform(X_test)

In [ ]:
#Convert non-numeric variables into dummies variables
import pandas as pd
# Assuming your DataFrame is called df
categorical_features = [
"Main_Building",
"Secondary School Quintile",
"Matric Province",
"Matric Year",
"Language Name",
"Ften Status This Year",
"Previous Activity Desc","Ethnic Group Name"]
# One-hot encode the categorical features
df3= pd.get_dummies(df3, columns=categorical_features,drop_first=True)

In [ ]:
print(df3.shape)

In [ ]:
# drop Transaction Date
df3=df3.drop(columns="Transaction Date")

In [ ]:
df3.select_dtypes(exclude=['number']).columns.tolist()

In [ ]:
#Remove constant and Quasi-constant features
from sklearn.feature_selection import VarianceThreshold
import pandas as pd

# Fit the selector
selector = VarianceThreshold(threshold=0.01)
df_D4_enc_reduced1 = selector.fit_transform(df3)
# Get the retained column names
selected_columns = df3.columns[selector.get_support()]
# Convert back to DataFrame
df_D4_enc_reduced1 = pd.DataFrame(df_D4_enc_reduced1, columns=selected_columns)
# Optional: check shape and preview
print(df_D4_enc_reduced1.shape)
print(df_D4_enc_reduced1.head())

In [ ]:
df3.select_dtypes(include=['object']).columns

In [ ]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

# One-hot encode the categorical column
df3_encoded = pd.get_dummies(df3, drop_first=True)

# Apply VarianceThreshold
selector = VarianceThreshold(threshold=0.01)
reduced_data = selector.fit_transform(df3_encoded)

# Keep selected columns
selected_columns = df3_encoded.columns[selector.get_support()]
df_D4_enc_reduced1 = pd.DataFrame(reduced_data, columns=selected_columns)

# Check results
print("Original shape:", df3_encoded.shape)
print("Reduced shape:", df_D4_enc_reduced1.shape)
print(df_D4_enc_reduced1.head())

In [ ]:
df3.head(5)

In [ ]:
df3[['Cohort Year', 'Completion Time']].dtypes

In [ ]:
df3['Cohort Year'] = pd.to_numeric(df3['Cohort Year'], errors='coerce')

NameError: name 'df3' is not defined

In [ ]:
df3['Completion Time'].unique()

In [ ]:
df3 = pd.get_dummies(df3, columns=['Completion Time'], drop_first=True)

In [ ]:
###CHECK FOR PERFECT OR NEARLY PERFECT CORRELATION
import numpy as np
import pandas as pd

# Step 1: Compute correlation matrix
corr_matrix = df_D4_enc_reduced1.corr().abs()

# Step 2: Extract upper triangle (to avoid duplicate pairs)
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Step 3: Identify columns to drop (correlation > 0.95)
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]

# Step 4: Drop columns
df_D4_enc_reduced2 = df_D4_enc_reduced1.drop(columns=to_drop)

# Step 5: Display results
print(f"❌ Removed due to high correlation ({len(to_drop)}):")
print(to_drop)

print(f"\n✅ Remaining columns ({df_D4_enc_reduced2.shape[1]}):")
print(df_D4_enc_reduced2.columns.tolist())

print(f"\n📐 New shape: {df_D4_enc_reduced2.shape}")
print(df_D4_enc_reduced2.head())

In [ ]:
from sklearn.model_selection import train_test_split
# Define X and y from the original dataset
y = df_D4_enc_reduced2['Minimum Time'] # Target variable
X = df_D4_enc_reduced2.drop(columns=['Minimum Time']) # Feature matrix
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.25, random_state=42, stratify=y # stratify if classification
)
print("X train", X_train.shape)
print("y test", y_train.shape)
print("X test", X_test.shape)
print("y test", y_test.shape)

NameError: name 'df_D4_enc_reduced2' is not defined


## Feature scaling: Apply log1p + MinMax scaling only on Numeric_cols

- np.log1p(x) is equivalent to log(x + 1) — it avoids issues with zero values. It reduces the impact of large values and spreads out smaller ones. After log transformation, the distribution becomes more balanced.
- Min-Max Scaling: This ensures: All values are between 0 and 1. The scale reflects relative differences more fairly. Outliers don’t distort the range

In [ ]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

# Step 1: Fit the selector
selector = VarianceThreshold(threshold=0.01)
selector.fit(df3_encoded)

# Step 2: Get retained and removed columns
selected_columns = df3_encoded.columns[selector.get_support()]
removed_columns = df3_encoded.columns[~selector.get_support()]

# Step 3: Transform the data
df_D4_enc_reduced1 = pd.DataFrame(selector.transform(df3_encoded), columns=selected_columns)

# Step 4: Display results
print(f"✅ Retained columns ({len(selected_columns)}):")
print(selected_columns.tolist())

print(f"\n❌ Removed columns ({len(removed_columns)}):")
print(removed_columns.tolist())

print(f"\n📐 New shape: {df_D4_enc_reduced1.shape}")
print(df_D4_enc_reduced1.head())

In [ ]:
removed_cols=removed_columns.tolist()
removed_cols

In [ ]:
numeric_cols

NameError: name 'numeric_cols' is not defined

In [ ]:
### Deducting nearly and constant features from numeric_cols list (original numeric column)

# Step 1: Find intersection
intersection = list(set(numeric_cols) & set(removed_cols))

# Step 2: Deduct intersection from numeric_cols
filtered_numeric_cols = [col for col in numeric_cols if col not in intersection]

# Step 3: Display results
print(f"🔗 Intersection (columns removed from numeric_cols): {intersection}")
print(f"📊 Updated numeric_cols ({len(filtered_numeric_cols)}): {filtered_numeric_cols}")

NameError: name 'numeric_cols' is not defined

In [ ]:
to_drop

NameError: name 'to_drop' is not defined

In [ ]:
## deducting highly correlated columns from numeric_cols list (original numberic columns)

# Step 1: Find intersection
intersection2 = list(set(filtered_numeric_cols) & set(to_drop))

# Step 2: Deduct intersection from numeric_cols
filtered_numeric_cols2 = [col for col in filtered_numeric_cols if col not in intersection2]

# Step 3: Display results
print(f"🔗 Intersection (columns removed from numeric_cols): {intersection2}")
print(f"📊 Updated numeric_cols ({len(filtered_numeric_cols)}): {filtered_numeric_cols2}")

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

scaler = MinMaxScaler()

for col in filtered_numeric_cols2:
    # Ensure column is numeric
    X_train[col] = pd.to_numeric(X_train[col], errors='coerce')
    X_test[col] = pd.to_numeric(X_test[col], errors='coerce')

    # Replace NaNs with 0 or a small positive value to avoid log errors
    X_train[col] = X_train[col].fillna(0)
    X_test[col] = X_test[col].fillna(0)

    # Log transform (log1p safely handles zeros)
    train_log = np.log1p(X_train[col])
    test_log = np.log1p(X_test[col])

    # Fit and apply scaling
    scaler.fit(train_log.values.reshape(-1, 1))
    X_train[col] = scaler.transform(train_log.values.reshape(-1, 1))
    X_test[col] = scaler.transform(test_log.values.reshape(-1, 1))

NameError: name 'filtered_numeric_cols2' is not defined

**Feature selection using feature importance of xgboost**

In [ ]:
 # 3. feature selection using feature importance of xgboost
from xgboost import XGBClassifier
import pandas as pd
model = XGBClassifier()
model.fit(X_train, y_train)
importance = pd.Series(model.feature_importances_, index=X.columns)
#This keeps only features with above-average importance, which balances pruning with performance.
threshold = importance.mean() # You can also try 0.01 or importance.median()
selected_features = importance[importance > threshold].index
X_xgb_train = X_train[selected_features]
X_xgb_test = X_test[selected_features]
print(f"Selected {len(selected_features)} features out of {X.shape[1]}")
print("X_xgb_train", X_xgb_train.shape)
print("X_xgb_test", X_xgb_test.shape)

**FEATURE SELECTION USING RANDOM FOREST**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
#import numpy as np


# Step 2: Apply log1p + MinMax scaling only to selected columns
scaler = MinMaxScaler()

for col in filtered_numeric_cols2:
    # Log transform
    train_log = np.log1p(X_train[col])
    test_log = np.log1p(X_test[col])

    # Fit scaler on training data
    train_scaled = scaler.fit_transform(train_log.values.reshape(-1, 1))
    test_scaled = scaler.transform(test_log.values.reshape(-1, 1))

    # Replace original columns with scaled values
    X_train[col] = train_scaled
    X_test[col] = test_scaled

**FEATURE SELECTION USING LOGISTIC REGRESSION**

In [ ]:
import warnings
# Suppress all warnings
warnings.filterwarnings('ignore')
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
rfe = RFE(LogisticRegression(), n_features_to_select=17)
rfe.fit(X_train, y_train)
X_LogReg_train = X_train.loc[:, rfe.support_]
X_LogReg_test = X_test.loc[:, rfe.support_]
print("X_LogReg_train",X_LogReg_train.shape)
print("X_LogReg_test",X_LogReg_test.shape)

NameError: name 'X_train' is not defined

**OVERSAMPLING USING SMOTE**

In [ ]:
from imblearn.over_sampling import SMOTE
# Step 1: Initialize SMOTE
smote = SMOTE(sampling_strategy={0: 300, 1: 300}, random_state=42)
# Step 2: Apply SMOTE to the encoded training set
X_xgb_train2, y_xgb_train2 = smote.fit_resample(X_xgb_train, y_train)
X_rf_train2, y_rf_train2 = smote.fit_resample(X_rf_train, y_train)
X_LogReg_train2, y_LogReg_train2 = smote.fit_resample(X_LogReg_train, y_train)
print(X_xgb_train2.shape, y_xgb_train2.shape)
print(X_rf_train2.shape, y_rf_train2.shape)
print(X_LogReg_train2.shape, y_LogReg_train2.shape)

NameError: name 'X_xgb_train' is not defined

**MACHINE LEARNING**

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
xgb_modelT2 =XGBClassifier(
    max_depth=2,
    n_estimators=2,
    learning_rate=0.1,
    subsample=0.7,
    colsample_bytree=0.7,
    reg_alpha=0.0,
    reg_lambda=0.0,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)
scores = cross_val_score(xgb_modelT2, X_xgb_train2, y_xgb_train2, cv=3, scoring="accuracy")#'f1')
print(f"Cross-validated accuracy: {scores.mean():.4f}")
print(f"Cross-validated scores cv 3: {scores}")

In [ ]:
# Train the model on the full resampled training set
xgb_modelT2.fit(X_xgb_train2, y_xgb_train2)

from sklearn.metrics import f1_score, classification_report

# Predict on test and training sets
y_test_pred = xgb_modelT2.predict(X_xgb_test)
y_train_pred = xgb_modelT2.predict(X_xgb_train2)

# F1 Score (Test Set)
f1_test = f1_score(y_test, y_test_pred)
f1_test_macro = f1_score(y_test, y_test_pred, average='macro')
f1_test_weighted = f1_score(y_test, y_test_pred, average='weighted')
f1_test_per_class = f1_score(y_test, y_test_pred, average=None)

# F1 Score (Training Set)
f1_train = f1_score(y_xgb_train2, y_train_pred)
f1_train_macro = f1_score(y_xgb_train2, y_train_pred, average='macro')
f1_train_weighted = f1_score(y_xgb_train2, y_train_pred, average='weighted')
f1_train_per_class = f1_score(y_xgb_train2, y_train_pred, average=None)

# Print results
print("🔍 F1 Scores on Test Set")
print(f"Overall F1 Score: {f1_test:.4f}")
print(f"Macro F1 Score: {f1_test_macro:.4f}")
print(f"Weighted F1 Score: {f1_test_weighted:.4f}")
print(f"F1 Score per class [No, Yes]: {f1_test_per_class}")

print("\n🔍 F1 Scores on Training Set")
print(f"Overall F1 Score: {f1_train:.4f}")
print(f"Macro F1 Score: {f1_train_macro:.4f}")
print(f"Weighted F1 Score: {f1_train_weighted:.4f}")
print(f"F1 Score per class [No, Yes]: {f1_train_per_class}")

# Optional: Full classification reports
print("\n📊 Classification Report (Test Set)")
print(classification_report(y_test, y_test_pred, target_names=["No", "Yes"]))

print("\n📊 Classification Report (Training Set)")
print(classification_report(y_xgb_train2, y_train_pred, target_names=["No", "Yes"]))

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Predict on test set
y_test_pred = xgb_modelT2.predict(X_xgb_test)

# Step 2: Compute confusion matrix
cm = confusion_matrix(y_test, y_test_pred)

# Step 3: Plot it with manual labels
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=["No", "Yes"], yticklabels=["No", "Yes"])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
from xgboost import plot_importance

# Plot feature importance
plt.figure(figsize=(10, 6))
plot_importance(xgb_modelT2, max_num_features=10, importance_type='weight')  # or 'gain', 'cover'
plt.title("XGBoost Feature Importance")
plt.tight_layout()
plt.show()

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
xgb_modelT3 =XGBClassifier(
    max_depth=2,
    n_estimators=2,
    learning_rate=0.05,
    subsample=0.6,
    colsample_bytree=0.5,
    reg_alpha=2,
    reg_lambda=1,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)
scores = cross_val_score(xgb_modelT3, X_xgb_train2, y_xgb_train2, cv=3, scoring="accuracy")#'f1')
print(f"Cross-validated accuracy: {scores.mean():.4f}")
print(f"Cross-validated scores cv 3: {scores}")
# Train the model on the full resampled training set
xgb_modelT3.fit(X_xgb_train2, y_xgb_train2)

from sklearn.metrics import f1_score, classification_report

# Predict on test and training sets
y_test_pred = xgb_modelT3.predict(X_xgb_test)
y_train_pred = xgb_modelT3.predict(X_xgb_train2)

# F1 Score (Test Set)
f1_test = f1_score(y_test, y_test_pred)
f1_test_macro = f1_score(y_test, y_test_pred, average='macro')
f1_test_weighted = f1_score(y_test, y_test_pred, average='weighted')
f1_test_per_class = f1_score(y_test, y_test_pred, average=None)

# F1 Score (Training Set)
f1_train = f1_score(y_xgb_train2, y_train_pred)
f1_train_macro = f1_score(y_xgb_train2, y_train_pred, average='macro')
f1_train_weighted = f1_score(y_xgb_train2, y_train_pred, average='weighted')
f1_train_per_class = f1_score(y_xgb_train2, y_train_pred, average=None)

# Print results
print("🔍 F1 Scores on Test Set")
print(f"Overall F1 Score: {f1_test:.4f}")
print(f"Macro F1 Score: {f1_test_macro:.4f}")
print(f"Weighted F1 Score: {f1_test_weighted:.4f}")
print(f"F1 Score per class [No, Yes]: {f1_test_per_class}")

print("\n🔍 F1 Scores on Training Set")
print(f"Overall F1 Score: {f1_train:.4f}")
print(f"Macro F1 Score: {f1_train_macro:.4f}")
print(f"Weighted F1 Score: {f1_train_weighted:.4f}")
print(f"F1 Score per class [No, Yes]: {f1_train_per_class}")

# Optional: Full classification reports
print("\n📊 Classification Report (Test Set)")
print(classification_report(y_test, y_test_pred, target_names=["No", "Yes"]))

print("\n📊 Classification Report (Training Set)")
print(classification_report(y_xgb_train2, y_train_pred, target_names=["No", "Yes"]))

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Predict on test set
y_test_pred = xgb_modelT3.predict(X_xgb_test)

# Step 2: Compute confusion matrix
cm = confusion_matrix(y_test, y_test_pred)

# Step 3: Plot it with manual labels
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=["No", "Yes"], yticklabels=["No", "Yes"])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
from xgboost import plot_importance

# Plot feature importance
plt.figure(figsize=(10, 6))
plot_importance(xgb_modelT3, max_num_features=10, importance_type='weight')  # or 'gain', 'cover'
plt.title("XGBoost Feature Importance")
plt.tight_layout()
plt.show()

**RANDOM FOREST**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, f1_score

# Step 1: Initialize the model
rf_model = RandomForestClassifier(
    n_estimators=12,
    max_depth=2,
    random_state=42,
    min_samples_leaf=1
)

# Step 2: Train on resampled training data
rf_model.fit(X_rf_train2, y_rf_train2)

# Step 3: Predict on training set
y_rf_train_pred = rf_model.predict(X_rf_train2)
train_accuracy = accuracy_score(y_rf_train2, y_rf_train_pred)
print(f"✅ Train Accuracy: {train_accuracy:.4f}")

# Step 4: Predict on test set
y_rf_test_pred = rf_model.predict(X_rf_test)
test_accuracy = accuracy_score(y_test, y_rf_test_pred)
print(f"✅ Test Accuracy: {test_accuracy:.4f}")

# Step 5: F1 Scores
f1_train = f1_score(y_rf_train2, y_train_pred)
f1_train_macro = f1_score(y_rf_train2, y_train_pred, average='macro')
f1_train_weighted = f1_score(y_rf_train2, y_train_pred, average='weighted')
f1_train_per_class = f1_score(y_rf_train2, y_train_pred, average=None)

f1_test = f1_score(y_test, y_test_pred)
f1_test_macro = f1_score(y_test, y_rf_test_pred, average='macro')
f1_test_weighted = f1_score(y_test, y_rf_test_pred, average='weighted')
f1_test_per_class = f1_score(y_test, y_rf_test_pred, average=None)

# Step 6: Print F1 Scores
print("\n🔍 F1 Scores (Train Set)")
print(f"Overall F1 Score: {f1_train:.4f}")
print(f"Macro F1 Score: {f1_train_macro:.4f}")
print(f"Weighted F1 Score: {f1_train_weighted:.4f}")
print(f"F1 Score per class [No, Yes]: {f1_train_per_class}")

print("\n🔍 F1 Scores (Test Set)")
print(f"Overall F1 Score: {f1_test:.4f}")
print(f"Macro F1 Score: {f1_test_macro:.4f}")
print(f"Weighted F1 Score: {f1_test_weighted:.4f}")
print(f"F1 Score per class [No, Yes]: {f1_test_per_class}")

# Step 7: Classification Reports
print("\n📊 Classification Report (Train Set):")
print(classification_report(y_rf_train2, y_rf_train_pred, target_names=["No", "Yes"]))

print("\n📊 Classification Report (Test Set):")
print(classification_report(y_test, y_rf_test_pred, target_names=["No", "Yes"]))

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Predict on test set
y_rf_test_pred = rf_model.predict(X_rf_test)

# Step 2: Compute confusion matrix
cm = confusion_matrix(y_test, y_rf_test_pred)

# Step 3: Plot it with manual labels
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=["No", "Yes"], yticklabels=["No", "Yes"])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Get feature importances
importances = rf_model.feature_importances_

# Get feature names (assuming X_train_resampled is a DataFrame)
feature_names = X_rf_train2.columns

# Create a DataFrame for easy sorting and plotting
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

# Plot
plt.figure(figsize=(10, 6))
plt.barh(importance_df['Feature'], importance_df['Importance'], color='skyblue')
plt.xlabel('Importance Score')
plt.title('Random Forest Feature Importance')
plt.gca().invert_yaxis()  # Highest importance at the top
plt.tight_layout()
plt.show()

**LOGISTIC REGRESSION**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, f1_score

# Step 1: Initialize the model
logreg_model = LogisticRegression(
    penalty='l2',
    solver='liblinear', #'liblinear','lbfgs'
    random_state=42
)

# Step 2: Train on resampled data
logreg_model.fit(X_LogReg_train2, y_LogReg_train2)

# Step 3: Predict on training set
y_LogReg_train_pred = logreg_model.predict(X_LogReg_train2)
train_accuracy = accuracy_score(y_LogReg_train2, y_LogReg_train_pred)
print(f"✅ Train Accuracy: {train_accuracy:.4f}")

# Step 4: Predict on test set
y_LogReg_test_pred = logreg_model.predict(X_LogReg_test)
test_accuracy = accuracy_score(y_test, y_LogReg_test_pred)
print(f"✅ Test Accuracy: {test_accuracy:.4f}")

# Step 5: F1 Scores
f1_train = f1_score(y_LogReg_train2, y_train_pred)
f1_train_macro = f1_score(y_LogReg_train2, y_LogReg_train_pred, average='macro')
f1_train_weighted = f1_score(y_LogReg_train2, y_LogReg_train_pred, average='weighted')
f1_train_per_class = f1_score(y_LogReg_train2, y_LogReg_train_pred, average=None)

f1_test = f1_score(y_test, y_test_pred)
f1_test_macro = f1_score(y_test, y_LogReg_test_pred, average='macro')
f1_test_weighted = f1_score(y_test, y_LogReg_test_pred, average='weighted')
f1_test_per_class = f1_score(y_test, y_LogReg_test_pred, average=None)

# Step 6: Print F1 Scores
print("\n🔍 F1 Scores (Train Set)")
print(f"Overall F1 Score: {f1_train:.4f}")
print(f"Macro F1 Score: {f1_train_macro:.4f}")
print(f"Weighted F1 Score: {f1_train_weighted:.4f}")
print(f"F1 Score per class [No, Yes]: {f1_train_per_class}")

print("\n🔍 F1 Scores (Test Set)")
print(f"Overall F1 Score: {f1_test:.4f}")
print(f"Macro F1 Score: {f1_test_macro:.4f}")
print(f"Weighted F1 Score: {f1_test_weighted:.4f}")
print(f"F1 Score per class [No, Yes]: {f1_test_per_class}")

# Step 7: Classification Reports
print("\n📊 Classification Report (Train Set):")
print(classification_report(y_LogReg_train2, y_LogReg_train_pred, target_names=["No", "Yes"]))

print("\n📊 Classification Report (Test Set):")
print(classification_report(y_test, y_LogReg_test_pred, target_names=["No", "Yes"]))

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Predict on test set
y_LogReg_test_pred = logreg_model.predict(X_LogReg_test)

# Step 2: Compute confusion matrix
cm = confusion_matrix(y_test, y_LogReg_test_pred)

# Step 3: Plot it with manual labels
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=["No", "Yes"], yticklabels=["No", "Yes"])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.tight_layout()
plt.show()

In [ ]:
import pandas as pd
import numpy as np

# Step 1: Get feature names (assuming X_train_resampled is a DataFrame)
feature_names = X_LogReg_train2.columns

# Step 2: Get coefficients from the trained model
coefficients = logreg_model.coef_[0]  # For binary classification

# Step 3: Create a DataFrame for easy viewing
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Coefficient': coefficients,
    'Abs_Coefficient': np.abs(coefficients)
})

# Step 4: Sort by absolute value (strongest influence)
importance_df_sorted = importance_df.sort_values(by='Abs_Coefficient', ascending=False)

# Step 5: Display top features
print(importance_df_sorted.head(10))

In [ ]:
import matplotlib.pyplot as plt

# Step 1: Sort coefficients by absolute value
importance_df_sorted = importance_df.sort_values(by='Abs_Coefficient', ascending=True)

# Step 2: Plot
plt.figure(figsize=(10, 6))
plt.barh(importance_df_sorted['Feature'], importance_df_sorted['Coefficient'], color='skyblue')
plt.axvline(x=0, color='gray', linestyle='--')  # Reference line at 0
plt.title('Logistic Regression Coefficients')
plt.xlabel('Coefficient Value')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

In [ ]:
Positive coefficients → push prediction toward "Yes" (class 1).

Negative coefficients → push prediction toward "No" (class 0).

Larger absolute values → stronger influence on the decision.